### ISSUE TITLE
Twitch Plugin frequently logs out and has to be reconnected

### ISSUE THREAD

**Issue by KhaldorTV** [Loupedeck-open-source/Loupedeck-Twitch-OpenPlugin#5]
As previously discussed, the Twitch Plugin does not reliably stay logged in.

**Comment by laperie** [comment]
There is something that prevents Twitch from using refresh token sometimes. It needs to be investigated.

**Comment by laperie** [comment]
Fixed in release 5.6.2.20005.   Authentication scheme replaced

**Comment by laperie** [comment]
should be closed by recent PR
